### ISSUE TITLE
Create a new 'pcyl' repo

### ISSUE THREAD

**Issue by 1fifoto** [grumpyinca/firstrepo#1]
We need to create a new 'pcyl' repo for our first joint attempt at doing something useful. I need for Mike to do this so that it is owned by him, otherwise I would do it. That's why I marked it 'help wanted'. Also I was testing out labels - ha!

**Comment by 1fifoto** [comment]
This is a second test comment to this issue. Hopefully Mike will see these comments and add his own comment to this issue as a test. Since the issue has a number, we should use the number as our branch name in the future if we need to make a code change for this issue. However, for this specific issue we probably never will need that.

**Comment by 1fifoto** [comment]
# I'm guessing that this uses markdown

* item 1
* item 2

To make tables uses vertical bar symbols

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

Or links

[I'm an inline-style link to Google](https://www.google.com)

Or code

    console.log("Hello World from Mike");
    console.log("I am learning about GitHub today !");
    console.log("This is our change from Eclipse");
    console.log("This is our change from Eclipse on branch test");
    console.log("This is our change from Eclipse on master");

**Comment by grumpyinca** [comment]
pcyl repository created with Public and MIT license properties.  Bri invited as collaborator. If no concerns, feel free to close the issue.

**Comment by grumpyinca** [comment]
When the pcyl repository was created, I set "gitignore" to Node.  However, I notice that when positioned on my GitHub "home page", firstrepo is marked as "JavaScript" but pcyl is not.  Did I miss doing something ?

**Comment by 1fifoto** [comment]
I added an dummy/empty index.js file and now it says "JavaScript".
